- layout/mainmenu.xml
Thought I'd done this already, apparently not.
> fix: Update Discord URL

- .gitignore
- layout/controlslibrary.xml
- layout/mainmenu.xml
- layout/mainmenu/mapselector/selector.xml
- layout/mainmenu_news.xml
- layout/popups/popup_lobbycreate.xml
- layout/popups/popup_lobbysettings.xml
- scripts/controlslibrary.js
- scripts/intromovie.js
- scripts/loadingscreen.js
- scripts/mainmenu.js
- scripts/mainmenu/mapselector/map_entry.js
- scripts/mainmenu_mapselector.js
- scripts/mainmenu_news.js
- scripts/mainmenu_settings.js
- scripts/popup/lobby_create.js
- scripts/popup/lobby_settings.js
- styles/pages/mainmenu.scss
Now 0.9.1 is basically done I wanted to go through all our old JS and improve the quality of the code.
Also includes a quick fix for https://github.com/momentum-mod/game/issues/1755
> Miscellaneous JavaScript cleanup

- scripts/mainmenu.js
During the code cleanup I changed a `let` to a `const` somehow...
> fix: Main Menu video error

- layout/hud/hud.xml
- layout/hud/synchronizer.xml
- layout/mainmenu_settings.xml
- layout/settings/settings_interface.xml
- scripts/common/panelregistration.js
- scripts/common/settings.js
- scripts/hud/synchronizer.js
- styles/hud/_index.scss
- styles/hud/hud.scss
- styles/hud/synchronizer.scss
I'm the world's biggest idiot and merged Peen's branch by accident. Reverted it, resubmitting the PR. Has my approval, needs 1 more.
Original message:
adds bhop trainer with 4 visualization modes and settings entries for feedback customization
fixup
> feat: Add synchronizer bhop trainer

- layout/hud/cgaz.xml
- layout/settings/settings_gameplay.xml
- scripts/hud/cgaz.js
- styles/hud/cgaz.scss
** C++ CHANGE REQUIRED **
This change:
- improves cgaz responsiveness
- cleans up ConVarEnabler use
- adds a setting for coloring the "uncolored" snap zones
- fixes vector normalization bug
- and sets the max height multiplier to 1x setting for sizing snaps by gain
> feat: better cgaz

- layout/settings/settings_video.xml
Resolves #27 
Code needs to be changed so the slider isn't greyed out when not in fullscreen don't merge until then, also #SFUI_Settings_Brightness_Info needs to be changed to explain the new convar.
> Change mat_monitorgamma to mat_brightness

- layout/mainmenu.xml
- scripts/mainmenu.js
Console commands for this have now been merged in on red, we can finally get rid of this ugly button!
> Remove Panorama persistent storage dump button

- layout/hud/hud.xml
- layout/hud/hudhinttext.xml
- styles/hud/_index.scss
- styles/hud/hudhinttext.scss
Allows env_hudhint to work again. Closes https://github.com/momentum-mod/game/issues/1376.
> Add HUD hint text

- styles/pages/console.scss
This depends on an internal MR
> fix(console): Fixes for console refactor

- layout/hud/bonecounts.xml
- layout/hud/hud.xml
- layout/hud/showpos.xml
- layout/showfps.xml
- styles/components/_index.scss
- styles/components/showfps.scss
- styles/hud/_index.scss
- styles/hud/bonecounts.scss
- styles/hud/showpos.scss
Closes https://github.com/momentum-mod/game/issues/1516
Merge with red PR
> Pano showfps, showpos, and showbonecounts panels

- images/chevron.svg
- layout/mainmenu.xml
- layout/mainmenu_settings.xml
- layout/settings/settings_audio.xml
- layout/settings/settings_gameplay.xml
- layout/settings/settings_input.xml
- layout/settings/settings_interface.xml
- layout/settings/settings_online.xml
- layout/settings/settings_search.xml
- layout/settings/settings_slider.xml
- layout/settings/settings_video.xml
- scripts/mainmenu.js
- scripts/mainmenu_settings.js
- scripts/settings_search.js
- scripts/settings_shared.js
- styles/components/settings.scss
- styles/pages/settings.scss
Been several things I've been wanting to do for ages, plus lots of localization related fixes.
Closes https://github.com/momentum-mod/game/issues/1942
Closes https://github.com/momentum-mod/game/issues/1613
Closes https://github.com/momentum-mod/game/issues/1878
Closes https://github.com/momentum-mod/game/issues/1909
Closes https://github.com/momentum-mod/game/issues/1908 once my red branch is in as well
> Settings improvements

- scripts/hud/cgaz.js
this PR fixes two bugs in the CGAZ implementation for defrag:
- Fixed defrag HUD elements not updating when `mom_df_hud_accel_enable` is OFF.
- Fixed js error caused by attempting to set css values to `NaN`px.
> CGAZ fixes

- layout/hud/ammo.xml
- layout/hud/hud.xml
- styles/hud/_index.scss
- styles/hud/ammo.scss
This PR adds a simple counter hud for the player's current ammunition.
> Ammo hud panel and styling

- scripts/chat.js
- styles/components/settings.scss
Closes https://github.com/momentum-mod/game/issues/1958
And a bit of cleanup
> Fix JS error when multiple typing in chat

- layout/settings/settings_video.xml
This pull request adds an entry under Video Settings for triple monitor mode.
Closes #18
> Add triple monitor mode to video settings

- layout/hud/spectate.xml
- scripts/drawer/lobby.js
I found a couple more that were wrong.
> fix: More spec icon paths

- README.md
Closes none
changes readme for clarity
pull request fixup as requested …
> chore: fix script dir location and update for clarity

- scripts/pages/drawer/lobby.js
Discovered this wasn't updated... now it is!
> fix: Update path for the steam.svg on user context menu

- .eslintrc.js
- package-lock.json
- package.json
- scripts/pages/end-of-run/end-of-run.js
- scripts/pages/learn.js
Just a few ESLint rules and auto fixes, and upgrades NPM packages. I'm going to rebase dontshowagain branch on top of this as this is so easy to get in and there's gonna be a conflict I want to resolve ASAP.
-   [x] All changes requested in review have been `fixup`ed …
> Minor ESLint changes + package update

- layout/util/toast-manager.xml
- scripts/util/functions.js
- scripts/util/toast-manager.js
- styles/modals/toasts/toast.scss
Closes momentum-mod/game/issues/1803
Closes momentum-mod/game/issues/1996
Closes momentum-mod/game/issues/1997
-   [x] Fully tokenized all my strings (no hardcoded English strings!!) …
> Misc fixes 1

- .github/pull_request_template.md
Tiny change to the PR template so Github recognises issues on the game repo properly so it can close them automatically.
> Update PR template to link game issues properly

- layout/hud/cgaz.xml
- scripts/hud/cgaz.js
Closes momentum-mod/game/issues/2029
Closes momentum-mod/game/issues/2019 (requires changes on red)
This pull request does a lot of background work in preparation for the Prime Sight feature which will dynamically show how each snap zone adds speed based on current velocity. Additionally, two regressions are fixed related to the defrag Compass element, and snapzone interaction with Haste as a pickup.
-   [x] My branch has a clear history of changes that can be easy to follow when being reviewed …
> Misc cgaz fixes

- layout/pages/leaderboards/leaderboards.xml
- scripts/pages/leaderboards/leaderboards.js
- styles/pages/leaderboards/leaderboards.scss
Closes momentum-mod/game/issues/2116
> feat: Added leaderboard track selection dropdown

- scripts/pages/main-menu/main-menu.js
Closes momentum-mod/game/issues/
-   [ ] Fully tokenized all my strings (no hardcoded English strings!!) and supplied [bulk JSON …
> Detect system color mode on first boot

- scripts/pages/settings/settings.js
Before:
After:
-   [X] **I have thoroughly tested all of the code I have modified/added/removed to ensure something else did not break**
-   [X] I have followed [semantic commit messages](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716) e.g. `feat: Add foo`, `chore: Update bar`, etc...
-   [X] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
-   [X] My branch is functionally complete; the only changes to be done will be those potentially requested in code review
-   [X] All changes requested in review have been `fixup`ed into my original commits.
-   [X] Fully tokenized all my strings (no hardcoded English strings!!) and supplied [bulk JSON strings](https://docs.momentum-mod.org/guide/localization/#bulk-adding-term …
> Fix style missing from panels inside a ConVarEnabler

- scripts/pages/zoning/zoning.ts
This PR corrects the BonusTrack property name to defragModifiers to match the zoning spec. It also introduces fixes for some zoning UI behavior related to defrag bonus tracks.
-   [x] …
> Fix defrag modifiers in zoning UI

- layout/hud/tab-menu.xml
- scripts/common/maps.ts
- scripts/hud/tab-menu.ts
- styles/hud/tab-menu.scss
I'm such an idiot, Panzer mentioned this already and I assumed it was because he was on the wrong branch. Woops!!
-   [x] Fully tokenized all my strings (no hardcoded English strings!!) …
> Fix tab menu credits exception

- layout/pages/map-selector/map-selector.xml
- styles/pages/map-selector/map-selector.scss
Woops I nuked a button
-   [x] Fully tokenized all my strings (no hardcoded English strings!!) and supplied [bulk JSON strings](https://docs.momentum-mod.org/guide/localization/#bulk-add …
> Fix map selector leaderboard button visibility

- scripts/hud/tab-menu.ts
- scripts/pages/map-selector/map-entry.ts
- styles/pages/map-selector/map-entry.scss
> 0.10.0 Panorama Misc

- layout/hud/tab-menu.xml
- layout/pages/leaderboards/leaderboards.xml
- scripts/common/leaderboard.ts
- scripts/hud/comparisons.ts
- scripts/pages/leaderboards/leaderboards.ts
-   [ ] Fully tokenized all my strings (no hardcoded English strings!!) and supplied [bulk JSON strings](https://docs.momentum-mod.org/guide/localization/#bulk-adding-terms) below
> Leaderboard fixes

- styles/pages/leaderboards/leaderboards.scss
This makes it possible to see more than just the top 10 local runs. …
> Add scrollbar to leaderboard

- scripts/components/player-card.ts
- scripts/pages/drawer/about.ts
- scripts/pages/drawer/profile.ts
- scripts/types-mom/apis.d.ts
- scripts/types-mom/events.d.ts
Small tweaks to `MomentumAPI`, see my PR on red.
> User data API tweaks

- scripts/pages/end-of-run/end-of-run.ts
Closes momentum-mod/game/issues/ …
> feat: Hook up watch replay button to MomTV

- layout/pages/map-selector/map-selector.xml
Hide MomKZ and KZT
-   [x] Fully tokenized all my strings (no hardcoded English strings!!) and supplied [bulk JSON strings](https://docs.momentum-mod.org/guide/localization/#bulk-adding- …
> Hide unfinished modes

- layout/pages/settings/online.xml
- scripts/pages/settings/page.ts
Removes the old shapes model code from settings and updates to new player model instead.
Also added primary/secondary color options.
-   [x] Fully tokenized all my strings (no hardcoded …
> feat: Update model settings with new player model & options

- scripts/hud/timer.ts
I'm in the process of cleaning this component up properly on another branch, but getting this in now since it causes an error on startup, and I want to ship an 0.10.0pre build.
> Stop registering nonexistent events

- layout/pages/settings/online.xml
Update comparison ghost cvars to have ghost in name
> Update ghost cvar settings

- scripts/pages/main-menu/news.ts
- styles/pages/main-menu.scss
Closes momentum-mod/game/issues/1990
See https://github.com/momentum-mod/game/issues/1990#issuecomment-2764620353
This probably didn't need to be in the 0.10.0 board but okay, nice to get out of the way.
> feat: improve news panel truncation and styling

- layout/pages/zoning/info.xml
- layout/pages/zoning/zoning.xml
- scripts/pages/zoning/zoning.ts
- styles/pages/zoning/zoning.scss
This PR adds functionality to the info panel displayed while creating/editing zones.
List of binds:
- Adjust grid size
- Adjust 3D crosshair distance
- Toggle two-click mode
- Override world geo/vertex snap
- Delete last placed point
- Select/Confirm
-   [x] All changes …
> Zoning info panel (binds list and action status)

- layout/pages/settings/audio.xml
Closes momentum-mod/game/issues/1721
> Update HRTF Enabler & Background Mute Slider

- scripts/components/range-color-display.ts
- scripts/modals/popups/import-export-settings.ts
- scripts/pages/drawer/drawer.ts
- scripts/pages/end-of-run/end-of-run.ts
- scripts/pages/main-menu/main-menu.ts
- scripts/pages/map-selector/map-entry.ts
- scripts/types-mom/events.d.ts
- scripts/util/event-definition.ts
- scripts/util/toast-manager.ts
Closes https://github.com/momentum-mod/game/issues/2299
Types repo PR here PR for types repo here https://github.com/StrataSource/pano-typed/pull/34/files
-   [x] Fully tokenized all my …
> Stronger event types

- layout/hud/hud.xml
- layout/hud/jump-timing.xml
- scripts/hud/jump-timing.ts
- scripts/types-mom/events.d.ts
- scripts/types-mom/panels.d.ts
- scripts/util/panel-registration.ts
- styles/config.scss
- styles/hud/_index.scss
- styles/hud/hud.scss
- styles/hud/jump-timing.scss
-   [ ] Fully tokenized all my strings (no hardcoded English strings!!) and supplied [bulk JSON strings](https://docs.momentum-mod.org/guide/localization/#bulk-adding-terms) below
> Jump timing indicator

- scripts/pages/zoning/zoning.ts
This PR fixes a problem with type guarding in zoning.ts which caused two JS errors. In one case, checking the selected zone was not relevant to the subsequent logic and in the other `!` was mistakenly converted to `!= null`.
-   [x] All changes requested in review have …
> Fix bonus type guard errors

- layout/pages/zoning/zoning.xml
- scripts/pages/zoning/zoning.ts
- scripts/types-mom/panels.d.ts
This PR fixes an issue with adding regions to an existing zone.
> fix zoning multiple regions in the same zone

- images/hud/safeguard-indicator.svg
- layout/hud/hud.xml
- layout/hud/safeguard-indicator.xml
- layout/pages/settings/gameplay.xml
- scripts/hud/safeguard-indicator.ts
- scripts/pages/main-menu/main-menu.ts
- scripts/types-mom/events.d.ts
- scripts/util/panel-registration.ts
- styles/hud/_index.scss
- styles/hud/hud.scss
- styles/hud/safeguard-indicator.scss
Radial meter for visualizing held safeguarded commands.
-   [ ] Fully tokenized all my strings (no hardcoded English strings!!) and supplied [bulk JSON …
> Safeguard hold visualizer

- images/panorama-outline.svg
- layout/components/gallery.xml
- layout/pages/map-selector/map-selector.xml
- scripts/components/gallery.ts
- scripts/pages/map-selector/map-selector.ts
- scripts/util/panel-registration.ts
- styles/config.scss
- styles/pages/map-selector/_index.scss
- styles/pages/map-selector/gallery.scss
- styles/pages/map-selector/map-selector.scss
Finally reviving this branch.
Closes https://github.com/momentum-mod/game/issues/1544
Closes https://github.com/momentum-mod/game/issues/2297
-   [x] Fully tokenized all my strings (no …
> Map selector gallery and changelog fixes

- scripts/pages/main-menu/main-menu.ts
- scripts/types-mom/apis.d.ts
- scripts/types-mom/events.d.ts
- styles/config.scss
Closes https://github.com/momentum-mod/game/issues/1890
Needs a red PR, will make shortly …
> Login failure popups

- layout/hud/safeguard-indicator.xml
- layout/pages/settings/gameplay.xml
- scripts/hud/safeguard-indicator.ts
- scripts/types-mom/events.d.ts
> Remove mom_hud_safeguard_indicator

- layout/pages/settings/online.xml
> Replay save settings

- styles/abstract/function.scss
- styles/core/utility.scss
- styles/pages/end-of-run.scss
- styles/pages/map-selector/map-selector.scss
Upgrading Sass compiler introduced a handful of warnings on launch, this fixes everything.
> Fix Sass deprecations

- layout/pages/settings/input.xml
-   [ ] Fully tokenized all my strings (no hardcoded English strings!!) and supplied [bulk JSON strings](https://docs.momentum-mod.org/guide/localization/#bulk-adding-terms) below
> Update start mark cvar

- layout/pages/controls-library.xml
- scripts/pages/controls-library.ts
- scripts/pages/map-selector/map-selector.ts
- scripts/types-mom/apis.d.ts
- scripts/types-mom/events.d.ts
- scripts/util/module-helpers.ts
- scripts/util/toast-manager.ts
- styles/modals/toasts/toast.scss
Closes momentum-mod/game/issues/2272
- Fixes toasts not being visible in the HUD
- Reverts to using C++-based ToastAPI instead of overcomplex JS-only approach
> Fix toasts not appearing on HUD

- layout/pages/map-selector/map-selector.xml
- layout/pages/settings/video.xml
- scripts/common/timer.ts
- scripts/pages/main-menu/main-menu-sounds.ts
- scripts/pages/map-selector/map-selector.ts
- scripts/pages/settings/settings.ts
- scripts/pages/settings/speedometer.ts
- scripts/types-mom/apis.d.ts
- styles/pages/map-selector/map-selector.scss
Closes momentum-mod/game/issues/2381
Closes momentum-mod/game/issues/2389
Closes momentum-mod/game/issues/2388
Fixes a bunch of small Panorama issues, mostly things introduced in the last update.
> Misc Panorama fixes

- scripts/hud/cgaz.ts
This pull request updates prime sight for VQ3, specifically half-beat strafing. …
> Implement VQ3 prime sight

- scripts/pages/drawer/lobby.ts
- scripts/pages/map-selector/map-entry.ts
- scripts/pages/map-selector/map-selector.ts
Couple tiny things, didn't have issues.
> Small pano fixes

- layout/pages/settings/interface.xml
- scripts/pages/settings/speedometer.ts
- scripts/util/module-helpers.ts
Closes momentum-mod/game/issues/2408
Turns out I introduced a massive bug when porting speedo settings to typescript and have been patching leaks ever since -- wasn't actually loading settings on load properly. Seems to fix everything now, plus adding some better null checking and fixed a few typos.
break**
-   [x] My branch is functionally complete; the only changes to be done will be those …
> Speedometer settings fixes

- layout/pages/settings/input.xml
> Update keybind settings

- layout/hud/map-info.xml
- scripts/hud/map-info.ts
Closes https://github.com/momentum-mod/game/issues/2418
> Show gamemode in map info panel

- layout/pages/main-menu/main-menu.xml
- scripts/pages/main-menu/main-menu-sounds.ts
- scripts/pages/main-menu/main-menu.ts
Closes momentum-mod/game/issues/2412
GameUI events are evil and fire all over the fucking place so need bunch of extra checks and faff
break**
review
-   [x] Fully tokenized all my strings (no …
> Fix main menu ambience in maps

- .github/pull_request_template.md
Adds context field to the PR template to incentivise usage of it (to help translators).
(Discussed in last meeting.)
Reference: https://poeditor.com/localization/files/json 
break**
review
-   [x] …
> chore(meta): add context field to PR template

- layout/pages/settings/video.xml
Donion rings
Closes https://github.com/momentum-mod/game/issues/2446
> fix: remove model/effect/shader detail settings

- layout/pages/settings/input.xml
We're getting rid of default menus because they suck :tada:
> chore: Rename hud menus for upcoming default removal change

- layout/pages/settings/audio.xml
Closes momentum-mod/game/issues/2468
break**
review
-   [x] Fully tokenized all my strings (no hardcoded English strings!!) and supplied
[bulk JSON …
> Add timer sounds to settings

- panorama.cfg
We use resource for it because VGUI uses some of the strings still too iirc?
> Point localization folder to proper folder

- layout/pages/main-menu/main-menu.xml
- scripts/pages/learn.ts
> fix: kill learn section
