- scripts/mainmenu.js
Stupid mistake, I was treating settings.mainMenuBackground as a bool here, but we store it as an int for if we want to add additional backgrounds in the future.
> fix: Main menu background switcher

- tools/get_latest_js_types.bat
- tools/get_latest_js_types.sh
Forgot to move this over to the public repo. Also re-ran on a new dumps files so will have a lot more types! (https://github.com/panorama-languages-support/panorama-jsdoc-gen/releases/tag/0.2.1)
> Add scripts to get js types file

- scripts/hud/cgaz.js
This PR fixes an old hack where snap shapes were only calculated at the first player input. Snap shapes are now correctly drawn when the Haste powerup is used.
Requires changes on Red.
> feat: Use haste timer to get snapzone shapes

- layout/hud/dfjump.xml
- layout/hud/hud.xml
- layout/settings/settings_gameplay.xml
- scripts/common/buttons.js
- scripts/common/panelregistration.js
- scripts/hud/dfjump.js
- styles/config.scss
- styles/hud/_index.scss
- styles/hud/dfjump.scss
This pull request adds a HUD element to aid jump timing in defrag.
- `mom_hud_jump_sync_enable` to draw jump sync bars - upward for late release, downward for early/late press.
- `mom_hud_jump_sync_max_delay` to set the max value for tracking jump presses. This is the value corresponding to 100% on either bar.
- `mom_hud_jump_sync_text_enable` to show time (ms) next to bars.
Requires Red changes to merge. Closes [#1793](https://github.com/momentum-mod/game/issues/1793)
> feat: Add Jump Sync defrag hud element

- layout/mainmenu.xml
- layout/mainmenu/mapselector/selector.xml
- styles/components/mapentry.scss
- styles/components/playercard.scss
- styles/pages/learn.scss
- styles/pages/mainmenu.scss
- styles/pages/mapselector.scss
- styles/pages/settings.scss
This change addresses issues https://github.com/momentum-mod/game/issues/1761 and https://github.com/momentum-mod/game/issues/1669, without the need to explicitly define aspect ratios. The menus scale for arbitrary aspect ratios between 1:1 and 21:9. For ratios larger than 21:9, the menu is displayed at 21:9 and centered on the screen - this has no effect for any display 21:9 or narrower.
> feat: adjust menus to scale better with aspect ratio

- layout/hud/cgaz.xml
- layout/settings/settings_gameplay.xml
- scripts/hud/cgaz.js
- styles/hud/cgaz.scss
This PR adds settings and functionality for compass hud elements in defrag:
- compass mode - off, show arrow, show ticks, show both
- compass size - compass tick length and arrow half-height
- pitch enable - show/hide pitch target
- pitch target - pitch line offset in degrees (71.8 default for plasma climb)
- compass stat mode - off, show pitch, show yaw, show both
- compass color - normal color for compass elements
- compass highlight color - pitch line & text set to this color when aiming at the pitch target, compass & yaw stat set to this color when velocity is along Pi/4 directions
Requires changes on red to function (cvars and events)
> Feat: defrag compass (pitch & yaw)

- scripts/common/eventdefinition.js
- scripts/common/run.js
- scripts/components/endofrun.js
- scripts/components/endofrun_xp.js
- scripts/components/graphs/linegraph.js
- scripts/hud/ghostentities.js
- scripts/hud/hud_leaderboards.js
- scripts/hud/speedometer.js
- scripts/mainmenu.js
- scripts/mainmenu_settings.js
- scripts/settings_search.js
- scripts/settings_speedometer.js
- scripts/toastmanager.js
- scripts/tooltips/credit.js
These are autogenerated comment spelling/grammar fixes. 
Two notes:
1. It was set to English-UK due to the spelling of initialise and such, so those inferior spellings are ignored.
2. This does not fix the fact that the methods like setComparisionStats() are misspelled, only the comments.
> Spelling Fixes

- scripts/hud/cgaz.js
This PR fixes a lingering a bug that should have been fixed with the last cgaz-fixes PR.
Defrag compass/pitch tools are now properly hidden outside of defrag.
Defrag compass/pitch tools now update when both snaps and accel zones are turned off.
> fix: stuck compass

- layout/hud/hud.xml
- layout/hud/jumpstats.xml
- layout/hud/synchronizer.xml
- layout/mainmenu_settings.xml
- layout/settings/settings_interface.xml
- scripts/common/panelregistration.js
- scripts/common/settings.js
- scripts/hud/jumpstats.js
- scripts/hud/synchronizer.js
- styles/config.scss
- styles/hud/_index.scss
- styles/hud/jumpstats.scss
- styles/hud/synchronizer.scss
This PR introduces a panel to implement jump stats like the SSJ plugin popular in CS:S. The ability to show jump stats on the strafe synchronizer is also introduced in this PR.
Jump stat settings:
- `mom_hud_jstats_enable` display bhop jump stats
- `mom_hud_jstats_first` first jump to log stats on jump stats panel
- `mom_hud_jstats_interval` log stats every X jumps after first log
- `mom_hud_jstats_takeoff_speed_enable` show takeoff speed on jump stats panel
- `mom_hud_jstats_speed_delta_enable` show speed delta on jump stats panel
- `mom_hud_jstats_takeoff_time_enable` show takeoff time on jump stats panel
- `mom_hud_jstats_time_delta_enable` show time delta on jump stats panel
- `mom_hud_jstats_strafe_sync_enable` show sync on jump stats panel
- `mom_hud_jstats_strafe_count_enable` show …
> feat: jump stats

- layout/hud/ammo.xml
closes https://github.com/momentum-mod/game/issues/1955
Requires internal PR to be merged first
> fix: Set ammo via dialog variable

- scripts/hud/cgaz.js
This pull request fixes two bugs with outline/mirror zone behavior:
- flickering while strafing
- wrong shape with Haste powerup
> Fix: mirror zones flickering and wrong shape with Haste

- layout/settings/settings_interface.xml
- scripts/hud/jumpstats.js
- scripts/hud/synchronizer.js
This pull request incorporates player feedback on the jump stats implementation.
- Updated display behavior to align with css. Jump stats are now printed on jump instead of on land.
- Only jump speed is printed on jump 1 (other stats are noise on the first jump)
- Added the option to color jump stats text on strafe synchronizer panel according to gain percentage (like jhud).
- Converted all ratio stats to show percentage  values.
- Fixed unlocalized text in strafe synchronizer settings
requires changes on red MR before merging.
> Bhop trainer improvements

- layout/chat.xml
Chat icon was using the wrong filename.
> fix: Chat spec icon

- layout/settings/settings_video.xml
```
"Settings_Video_PreventThreadSleep" "Prevent Thread Sleep"
"Settings_Video_PreventThreadSleep_Info" "Prevent the game thread from sleeping when at maximum FPS limit. Enabling this option results in higher CPU utilization and potentially smoother performance."
```
> Add sleep_when_meeting_framerate option to video settings

- scripts/hud/cgaz.js
Closes https://github.com/momentum-mod/game/issues/1986
This PR fixes a regression with the defrag pitch hud. The visibility setting on the pitch marker is now set to the correct value. …
> fix: missing pitch marker

- scripts/hud/cgaz.js
- scripts/hud/synchronizer.js
This PR fixes a regression caused by changing `isNaN()` to `Number.isNaN()` at every occurrence.
-   [ ] Fully tokenized all my strings (no hardcoded English strings!!) and supplied …
> fix: isNaN regression where js sets css properties

- layout/pages/settings/interface.xml
-   [ ] Fully tokenized all my strings (no hardcoded English strings!!) and supplied [bulk JSON strings](https://docs.momentum-mod.org/guide/localization/#bulk-adding-terms) below …
> fix: wrong term in Efficiency description slot

- .eslintrc.js
- scripts/hud/cgaz.js
This pull request enhances the functionality of snap hud for defrag. This pull request also lays the groundwork for the CGAZ 2.0 overhaul.
Changes:
- When using highlight mode 2, only the portion of the highlighted snap zone that can provide acceleration is colored
- Zones (snaps, CGAZ, mirror) are refactored as objects containing a reference to some panel, angles representing the left and right edges of that panel, and pixel values for the left and right edge of the panel on screen.
- Cleaned up member variable names to align with style convention (camelCase)
- Fix js error when scaling/interpolating across a range with 0 distance.
-   [x] I have followed [semantic …
> feat: enhanced snap highlight

- layout/hud/cgaz.xml
- scripts/hud/cgaz.js
- styles/hud/cgaz.scss
Closes #[1994](https://github.com/momentum-mod/game/issues/1994)
This pull request modifies the structure of pitch markers in the compass section of defrag HUD.
Changes:
- Pitch target convar is read as string and parsed into an array
- Panels are created or destroyed to match the size of the array of pitch angles to be marked
- The pitch stat is highlighted when the player aims within 0.1 degrees of any pitch target
THIS PR DEPENDS ON RED CHANGES.
-   [x] My branch has a clear history of changes that …
> feat: multi-pitch

- layout/hud/leaderboards.xml
- styles/hud/leaderboards.scss
- styles/pages/end-of-run.scss
[Closes #2006](https://github.com/momentum-mod/game/issues/2006#issue-1591093851)
[Closes #1764](https://github.com/momentum-mod/game/issues/1764#issue-1204260535)
Redoing this PR, having troubles w/ previous
fix: chose correct file location of an icon for a toast
(probably not going to matter when that feature is implemented and its deleted, but I'm just practicing git stuff)
feat: created label telling you to right-click to enable your cursor - in leaderboards/end of run panel
-bottom right of leaderboard (looks clearer in game)
-looks good in end of run panel as well
-   [x] I have followed [semantic commit …
> Add 'enable cursor' label tip to hud leaderboard + misc fix (redo)

- layout/pages/settings/interface.xml
- layout/pages/settings/settings.xml
- scripts/common/settings.js
Added damage indicator settings to the settings panel. …
> feat: Damage Indicator Settings

- scripts/hud/cgaz.js
Closes momentum-mod/game/issues/2012
This PR fixes a js error in the advanced snap target highlight code introduced with the last update.
-   [x] **I have (actually) thoroughly tested all of the code I have modified/added/removed to ensure something else did not break**
-   [x] Fully tokenized all my …
> fix: snap divide by zero

- images/hud/meter-ring.svg
- layout/hud/ground-boost.xml
- layout/hud/hud.xml
- scripts/hud/ground-boost.js
- scripts/util/panel-registration.js
- styles/hud/_index.scss
- styles/hud/ground-boost.scss
Closes momentum-mod/game/issues/2035 (convar implemented in red repo)
This PR adds a groundboost feature for defrag. The indicator shows when the player has the knockback flag (from weapon or teleporter) and changes state to show a successful crash landing to extend the defrag timer to max duration.
Currently intended to be implemented for testing and feedback - no settings UI included in this PR. The feature as implemented is only available through the console.
-   [x] My branch has a clear history of …
> Add groundboost indicator for defrag

- layout/hud/speedometer.xml
- layout/modals/popups/speedometer-select.xml
- layout/pages/settings/interface.xml
- scripts/common/speedometer.js
- scripts/hud/speedometer.js
- scripts/modals/popups/speedometer-select.js
- scripts/pages/settings/speedometer.js
- styles/hud/speedometer.scss
- styles/pages/settings/speedometer.scss
Closes https://github.com/momentum-mod/game/issues/1906
Closes https://github.com/momentum-mod/game/issues/1907
Closes https://github.com/momentum-mod/game/issues/1787
Closes https://github.com/momentum-mod/game/issues/1770
Unblocks https://github.com/momentum-mod/game/issues/1767
**Functionality rework**
We no longer have 1 speedometer for a set type. Rather, players can add multiple speedometers of a type (the overall velocity one and the event ones), give it a custom name, and control which axes they care about.
There has also been some consolidation, in that the energy speedometer and different units have been removed. Ramp board and exit have been consolidated into 1 speedometer type.
**New data format**
New kv3 format allows for much easier data parsing (arrays! in 2023! can you …
> New speedometer format

- scripts/hud/cgaz.js
Closes momentum-mod/game/issues/2039
This PR fixes a bug preventing CGAZ snap hud offset from being calculated correctly. …
> fix: snap offset decoupling from cgaz

- layout/hud/ground-boost.xml
- layout/pages/settings/gameplay.xml
- scripts/hud/ground-boost.js
- styles/hud/ground-boost.scss
Closes momentum-mod/game/issues/2040
This pull request improves the prototype behavior of the defrag groundboost indicator based on player feedback.
- HUD element is only toggled ON if the player is grounded
- HUD element is frozen when the player jumps
- Color is repurposed to show friction state instead of crashland state
- Added delay on fade out to help clarity
- Reduced background opacity to help clarity
- Added settings UI
-   [x] My branch has a clear history of changes that can be easy to …
> feat: Improve defrag groundboost indicator behavior

- scripts/hud/cgaz.js
- styles/hud/cgaz.scss
Closes momentum-mod/game/issues/2045
This pull request improves the behavior of the defrag pitch indicator. The root cause is not addressed - the pano bug needs to be investigated separately.
The changes in this pull request adjust panel behavior to address the bug outlined in issue 2045.
- Instead of using the edge of the panel to mark pitch target(s), the panel height is kept fixed and the border is not drawn.
- Panel is positioned with the `position` css property
This change is to be used as a prototype for improving the rest of the moving line/rectangle type defrag HUD elements. When cgaz.js is broken up into separate tools, this implementation should be adapted to the horizontal case.
-   [x] **I have thoroughly tested all of the code I have modified/added/removed to ensure something …
> fix: df pitch border bug

- layout/hud/ground-boost.xml
- layout/pages/settings/gameplay.xml
- scripts/hud/ground-boost.js
- styles/hud/ground-boost.scss
Closes momentum-mod/game/issues/2046
~Required Red changes!~ Engine changes merged.
This pull request adds features and settings for the defrag groundboost indicator.
- Added setting for choosing label data
- `mom_df_hud_gb_text_mode` 0 = OFF, 1 = Remaining time, 2 = Speed change
- Mode 1 is default (same as previous behavior)
- Added setting for coloring label text
- `mom_df_hud_gb_text_color_mode` 0 = OFF, 1 = Timer, 2 = Speed
- Mode 0 is default (same as previous behavior)
- Added setting for showing when the player stayed on the ground too long
- `mom_df_hud_gb_overshoot_enable`
- Default is ON (same as previous behavior)
- Added setting for distinguishing crash landing from other slick states
- `mom_df_hud_gb_crash_hl_enable`
- Default is OFF (same as previous behavior)
I've tested …
> Feat: Add defrag groundboost settings

- README.md
README.md contained a reference to Chaos. This was the only reference I could find (using the regex `[^<|/|"|']Chaos`) that wasn't code-related. Changing all the panel names (e.g. `ChaosSettingsSlider`) is a much bigger refactor and takes a ton of C++ work.
-   [x] All …
> fix: Replace Chaos reference in README.md with Strata

- scripts/hud/cgaz.js
- scripts/hud/ground-boost.js
Closes momentum-mod/game/issues/2058
This pull request updates UI logic to match recent changes to how haste is tracked by the engine. Instead of storing an ending timestamp, an integer value is passed as `lastMoveData.hasteTime` to communicate the number of milliseconds of haste remaining (-1 for unlimited haste).
-   [x] My branch is functionally complete; the only changes to be done will …
> fix: incorporate engine changes to haste time calculation

- layout/hud/cgaz.xml
- layout/pages/settings/gameplay.xml
- scripts/hud/cgaz.js
Depends on Red changes for convars!
This pull request adds Prime Sight UI for Defrag. Prime Sight is a combination of the CGAZ and snap HUDs from Q3DF which shows the following information in real time:
- Which regions allow the player to gain speed
- How the potential gain from each zone compares with the maximum
- When it's favorable to switch strafe directions to maximize speed gain
Settings for the following features are included:
- Size (height) of the HUD tool
- Offset from center screen
- Minimum speed to draw the HUD
- Colors for indicating potential speed gain/loss
- Color for indicating diagonal strafe zones not currently in use
- Highlighting the zone representing the current movement calculation
- Color for highlighting current active zone
- Disabling the relative gain scaling …
> Defrag Prime Sight

- scripts/hud/cgaz.js
Closes momentum-mod/game/issues/2078
Closes momentum-mod/game/issues/2079
This pull requests fixes a few bugs with the new prime sight hud for defrag.
- Highlighting now correctly selects the zone behind the crosshair at resolutions other than 1080p.
- The correct zone is shown when the zone wraps across -pi/pi (reported by lumia & panzer).
-   [x] My branch is functionally complete; the …
> prime sight fixes

- scripts/hud/cgaz.js
This reverts commit 11b129c2e77f8c5b475703355465390ad18fed04.
This PR reverts a "fix" to panel position and size calculations for defrag hud.
-   [x] Fully tokenized all my strings (no …
> Revert "fix: improve panel size and position rounding"

- layout/pages/settings/input.xml
- scripts/pages/settings/mouse-sensitivity.js
Closes momentum-mod/game/issues/2047
This PR adds conversion from in-game sensitivity to cm/360 and in/360 ( and vice-versa )
-   [x] Fully tokenized all my strings (no hardcoded …
> feat: add cm/360 sensitivity conversion

- scripts/pages/settings/mouse-sensitivity.js
If `settings.mouseDPI` is missing, this returns `null` which is gets stringified to `"null"`, and shows up in UI. Just coalescing to an empty string looks fine.
-   x] I have followed [semantic commit messages](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716) e.g. `feat: Add foo`, `chore: Update bar`, etc...
-   [x] Fully tokenized …
> fix: null coalesce settings.mouseDPI to empty string

- layout/pages/settings/video.xml
With https://github.com/StrataSource/Engine/issues/368 fixed, this can get re-enabled.
-   [ ] Fully tokenized all my strings (no hardcoded English strings!!) and supplied [bulk JSON …
> chore: Re-enable error cubemap dropdown

- layout/pages/settings/audio.xml
Updates Audio Settings page to work better with the sound system changes brae made a while ago.
- Rename "Game Volume" to "Master Volume" - clearest term for conveying that it affects everything.
- Removed "Player Weapon Volume", replaced with "Weapon Volume"
- Renamed "Overall Weapon Volume" to "Weapon Volume", fixed the convar to use correct one (`snd_volume_weapon`)
- Removed "Physics Volume" - nothing really uses this
- Added "Ghost Volume"
-   [x] My branch has a clear history of changes that can …
> refactor: Update audio settings sliders

- scripts/pages/learn.js
Closes momentum-mod/game/issues/1794 …
> feat: double click to start learn lesson

- domain_whitelist.kv3
~~Ties in to internal MR adding a whitelist to `AsyncWebRequest`, fine to merge *after that MR is in*~~
Internal MR has been merged, this should be merged before your next release
- …
> feat: add domain_whitelist.kv3

- layout/pages/settings/gameplay.xml
Closes https://github.com/momentum-mod/game/issues/951 (red has been merged already) …
> feat: Add mom_paint_color_from_normal setting

- layout/hud/cgaz.xml
- scripts/hud/cgaz.js
- styles/hud/cgaz.scss
Closes momentum-mod/game/issues/2100
This pull request changes the behavior of the compass HUD element to match the most recent version of the defrag pitch helper.
Previously, compass ticks were created as left and right borders of a panel. Now ticks are individual panels with fixed width. This prevents border properties from misbehaving when the color is changed.
-   [x] My branch is …
> fix: refactor compass ticks

- scripts/hud/cgaz.js
I recently fixed some ConVar access debugging stuff and saw that cgaz's `onUpdate` is always running, even when not on the Defrag gamemode. Let me know if there's a more correct way to fix this.
-   [x] All changes requested in review have been `fixup`ed into my original …
> fix: Don't do cgaz updates on modes that aren't defrag

- scripts/pages/settings/speedometer.js
This was because of a unicorn linter rule that got added and me subsequently ballsing up the refactor to appease it.
Closes momentum-mod/game/issues/2104
-   [x Fully tokenized all my …
> fix: always use /g in replaceAll using regexes

- scripts/pages/main-menu/main-menu.js
Currently the background runs from 25th to 31st, feels a bit short. Figured starting a week earlier would be a bit better, 2 weeks feels reasonable.
-   [x] Fully tokenized all my …
> Start Christmas background on 18th instead of 25th

- layout/modals/popups/speedometer-select.xml
- scripts/modals/popups/speedometer-select.js
- scripts/pages/settings/speedometer.js
Deleting a speedometer with the same name as an existing speedometer results in an `underlying object` js exception. This is because `this.detailObject.findIndex()` inside `deleteSpeedometer()` deletes the first speedometer matching the name of the selected speedometer. I have changed `speedometer-select.js` to check for these invalid names (mostly used the same code from range-color-profile-name.js). This also makes it consistent with  deleting and adding range profiles.
-   [x] My branch has a clear …
> fix: check for invalid speedometer names

- layout/pages/settings/interface.xml
- layout/pages/settings/settings.xml
- scripts/common/settings.js
Adds mom_hud_comparisons_enable to settings under interface/hud …
> Add comparisons to settings

- scripts/components/graphs/line-graph.js
- scripts/pages/end-of-run/end-of-run.js
- styles/components/graphs/linegraph.scss
- styles/config.scss
Closes momentum-mod/game/issues/1995
Made the time axis of the end of run graph use formatting based on the extents of the graph, using just seconds, `m:ss`, or `h:mm` where appropriate, and increased spacing slightly so that longer labels like `+mm:ss` don't shrink down.  
(Also, I used `$.Localize()` to check what stat is being compared and I'm not entirely sure if it's bad to do or not)
- …
> Display end-of-run graph time strings on y-axis

- scripts/hud/leaderboards.js
This now says the number of zones and runs (current api doesn't have runs afaik). Before it said zones Zones and runs Runs. …
> fix: Display zones and runs stats properly in leaderboards

- layout/pages/drawer/about.xml
- scripts/pages/drawer/about.js
- styles/pages/drawer/about.scss
Removes changelog from the about section in the drawer. It looks like this now.  …
> Remove changelog from about section

- tsconfig.json
Submodule doesn't install automatically when first cloning the repo - this comment reminds you if you need to do that …
> Add comment reminding devs to install the submodule

- tools/parseLearnSheet.py
Since we deleted the changelog.vdf file this directory no longer exists, causing release CI to fail.
> Make parseLearnSheet.py create /data directory if missing

- scripts/pages/learn.js
forgot to open this PR .. engine changes have been merged
> refactor: Remove mappingmode

- .github/workflows/format.yml
Workflow isn't being run for 0.10 branch, isn't enforcing formatting.
> Enable Code Quality workflow for PRs on all branches

- scripts/util/register-event-for-gamemodes.ts
Function we discussed yesterday that both Mac and Peen are using atm, so figured it's best I get this PRed ASAP.
-   [x] Fully tokenized all my strings (no hardcoded English strings!!) …
> RegisterEventForGamemode util function

- layout/hud/map-info.xml
- layout/hud/tab-menu.xml
- layout/pages/loading-screen.xml
- layout/pages/map-selector/map-selector.xml
- scripts/common/map-cache.js
- scripts/hud/map-info.js
- scripts/hud/tab-menu.js
- scripts/pages/loading-screen.js
- scripts/pages/map-selector/map-entry.js
- scripts/pages/map-selector/map-selector.js
- Use `UserMapData` for checking if the map file exists or is in favorites
- Lookup main track leaderboard since it no longer exists on the model
- Updated map data to be compatible with new backend models
> refactor: Misc fixes for API model updates

- layout/hud/tab-menu.xml
- layout/pages/zoning/zoning.xml
This pull request adds the requisite panels as skeletons for the upcoming zoning UI. Breaking changes were introduced in the engine-side code necessary for zone editing and UI. The empty panorama code introduced in this PR will be filled with zoning UI implementation in a future PR. The purpose of this MR is to add frontend changes necessary to prevent the 0.10 branch from breaking when merging such that the zoning UI can be tested on the 0.10 branch - potentially without red access.
Must be merged simultaneously with Red MR.
> prepare tab menu for upcoming in-game zoning UI

- scripts/pages/map-selector/map-selector.js
Comments out map selector filter saving code. Annoying to fix the issues on moving between base steam branch and `upcoming`, small enough feature that fine to just disable for now. Will be back in 0.10!
> fix: disable map selector filters until 0.10

- layout/pages/settings/video.xml
- scripts/pages/settings/fov.js
- scripts/pages/settings/settings.js
- scripts/util/math.ts
Closes momentum-mod/game/issues/2126
Adds a text box to change the horizontal FOV, which gets automatically converted to/from FOV.
-   [X] **I have thoroughly tested all of the code I have modified/added/removed to ensure something else did not break**
-   [X] I have followed [semantic commit messages](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716) e.g. `feat: Add foo`, `chore: Update bar`, etc...
-   [X] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
-   [X] My branch is functionally complete; the only changes to be done will be those potentially requested in code review
-   [X] All changes requested in review have been `fixup`ed into my original commits.
-   [X] Fully tokenized all my strings (no hardcoded …
> feat: add horizontal FOV converter

- scripts/pages/map-selector/map-selector.js
Fix a stupid JS exception, trying to access a var I deleted when disabling the filter save/load mechanism.
> Fix map filters JS exception

- layout/hud/cgaz.xml
- layout/hud/df-jump.xml
- layout/hud/ground-boost.xml
- layout/hud/jump-stats.xml
- layout/hud/synchronizer.xml
- scripts/hud/cgaz.js
- scripts/hud/df-jump.js
- scripts/hud/ground-boost.js
- scripts/hud/jump-stats.js
- scripts/hud/synchronizer.js
This pull request prevents some gamemode-specific hud elements from processing data outside of their intended modes …
> Check game modes for mode-specific hud panels

- images/vector-polyline.svg
- images/vector-two-click.svg
- layout/hud/tab-menu.xml
- layout/pages/zoning/zoning.xml
- scripts/hud/tab-menu.js
- styles/hud/tab-menu.scss
- styles/pages/zoning/zoning.scss
This pull request updates tabmenu and zoning UI to use new `ToggleButton` behavior. These menus no longer rely on `GameInterfaceAPI.ConsoleCommand()` or `GameInterfaceAPI.SetSettingBool()`.
Before removing draft tag, I'm looking for feedback on which icon to use for signifying that two-click mode is disabled. See discussion in #Zoning UI in momentum discord.
~~Depends on red panorama changes.~~ Red changes merged.
-   [x] My branch has a clear history of changes that can be easy to follow when being …
> convar togglebuttons and two-click styling

- layout/pages/zoning/zoning.xml
- scripts/pages/zoning/zoning.ts
This PR improves the following zoning UI features:
-  Ensure correct region menu is shown based on tab selection
-  Zoning edits only reset when "Cancel Edit" is clicked. Closing the zone menu no longer resets zone defs
-  Zones render changes as properties are modified
-  Newly created zones are initialized with default height
-  Picking a corner below the current region bottom updates the region bottom value
-  Point picking mode now shows visualization of region points before region is defined
Requires red changes to render zone visualization while picking points.
-   [x] I have followed [semantic commit messages](https://gist.github.com/joshbuchea/6f47e86d2510bce28f …
> region visualization and misc QoL

- layout/pages/map-selector/map-selector.xml
I messed something up with Git when changing map filter stuff on Steam branch last time, and forgot to commit this. For players who don't have the map selector filters extended already, hitting the "Filters" button causes a JS error and they don't get shown. 
This removes the button, and makes filters always visible.
Not a game-breaking bug (afaik nobody has actually reported it) but worth fixing.
> fix: make map selector filters always visible

- layout/hud/replay-controls.xml
- scripts/hud/replay-controls.ts
- scripts/types-mom/apis.d.ts
This converts the replay controls to control momtv replays. Not all prior functionality is supported yet.
> MomTV Replay Controls

- package-lock.json
- scripts/util/math.ts
This pull request updates the vector functions in `math.ts` to be more flexible with respect to vectors in 2D/3D. 2D functions can be called on 3D vectors ignoring the z component. Base functions will handle either 2D or 3D vectors.
-   [x] All changes requested in …
> vector stuff

- scripts/pages/map-selector/map-selector.js
I did the last fix for filters in a rush and didn't test properly, this fixes a JS error getting brought up. I've been really half-assing this since the 0.10.0 version completely rewrites this system. Spent some time just now testing properly, including with persistent storage empty, seems okay now. Sorry about this!
> Fix map selector filters AGAIN

- scripts/hud/comparisons.ts
- scripts/hud/spec-info.ts
- scripts/hud/spectate.ts
- scripts/hud/speedometer.ts
- scripts/hud/sticky-charge.ts
- scripts/hud/timer.ts
- scripts/types-mom/events.d.ts
- scripts/types-mom/panels.d.ts
Changes to go with part 2 of the game code cleanup:
- Remove `MomentumSpectatorTargetChanged` in favor of generic `ObserverTargetChanged` (depends on https://github.com/StrataSource/pano-typed/pull/24)
- Remove `currentRunData` and `currentRunStats` from `HudComparisons` (replaced by `MomentumTimer::GetObservedTimerStatus()` and `GetObservedTimerRunSplits()`)
- Remove `OnMomentumZoneChange` (replaced by new timer events)
- Remove `OnChargeToggled` and add `enabled` value to `OnChargeUpdate`
> September cleanup part 2

- scripts/pages/zoning/zoning.ts
- styles/pages/zoning/zoning.scss
This PR fixes an issue with the new pano zoning UI. Points can now be edited after placement with the textentry panels for the respective point.
-   [x] Fully tokenized all my strings …
> Fix points edit with textentry

- layout/hud/hud.xml
- scripts/hud/customizer.ts
- styles/hud/hud.scss
Added resizing to the hud customizer.
Most hud elements aren't resized properly, but the chat is.
There's a new size property that needs to be added to the hud_default.kv3
-   [X] **I have thoroughly tested all of the code I have modified/added/removed to ensure something else did not break**
-   [X] I have followed [semantic commit messages](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716) e.g. `feat: Add foo`, `chore: Update bar`, etc...
-   [X] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
-   [X] All changes requested in review have been `fixup`ed into my original commits.
-   [X] Fully …
> hud customizer: Add resizing

- scripts/types-mom/panels.d.ts
Types for some new game code utilities for the zone editor. validateRegionPolygon is only needed in the C++ side of the zone editor right now given the current design but it could foreseeably end up being needed in JS.
> feat: ZoneMenu utility functions

- scripts/common/timer.ts
- scripts/hud/comparisons.ts
- scripts/pages/end-of-run/end-of-run.ts
- scripts/pages/map-selector/map-selector.ts
- styles/components/split.scss
I will come back to this and add support for unordered/optional checkpoints and run stats comparisons.
-   [x] Fully tokenized all my strings (no hardcoded English strings!!) and …
> Timer splits for stages and ordered/required checkpoints

- layout/hud/tab-menu.xml
- layout/pages/zoning/zoning.xml
- scripts/pages/zoning/zoning.ts
- scripts/types-mom/apis.d.ts
- scripts/types-mom/panels.d.ts
- styles/hud/tab-menu.scss
- styles/pages/zoning/zoning.scss
This pull request implements several changes being tracked here:
https://github.com/momentum-mod/game/issues/2122
This can likely be reviewed by changes rather than by commit, but the history is preserved in case reviewers would like to see how this PR relates to the checklists in issue 2122.
REQUIRES SIMULTANEOUS RED CHANGES
Main changes:
- Only allow zoning UI to be opened when `sv_cheats` is enabled
- Styling improvements to tab menu related to zoning (hide header, padding, footer contents)
- Zoning UI styling improvements (bg colors, padding, indentation)
- Reworked add/delete functionality
- Buttons inline within tracklist tree
- Add buttons no longer selection dependent (add checkpoint to arbitrary segment)
- UX improvement for placing corners, set zone height
- Better communication …
> zoning UI cleanup part 1

- layout/pages/settings/gameplay.xml
> Noclip speed settings

- layout/pages/leaderboards/leaderboards.xml
- scripts/common/timer.ts
- scripts/components/graphs/line-graph.ts
- scripts/hud/comparisons.ts
- scripts/pages/end-of-run/end-of-run.ts
- scripts/pages/leaderboards/leaderboards.ts
- scripts/types-mom/events.d.ts
- styles/pages/leaderboards/leaderboards.scss
Updated the end of run menu to display splits and comparisons from the new timer system. …
> End of run menu for new timer system

- scripts/common/timer.ts
- scripts/hud/comparisons.ts
Checkpoints in linear maps were displaying as 1-1, 1-2, 1-3, etc. in the split comparison UI so I changed it to display just the subsegment number.
-   [x] Fully tokenized all my …
> Linear map checkpoints

- scripts/pages/end-of-run/end-of-run.ts
I will follow up with some improvements to the stage checkpoint splits so that they are evenly spaced and the x-axis has the appropriate labels ("4-1", "4-2", etc.)
Linear map:
Staged map:
-   [x] All changes requested in review have been `fixup`ed into my original …
> Add subsegment splits to end of run menu

- scripts/hud/df-jump.ts
- scripts/hud/ground-boost.ts
- scripts/hud/powerup-timer.ts
- scripts/hud/replay-controls.ts
- scripts/hud/synchronizer.ts
Addresses regressions made in commits [b46c6b5](https://github.com/momentum-mod/panorama/commit/b46c6b5ed69926172d347eabb8ee79c2b020a7a8) and [af37ff6](https://github.com/momentum-mod/panorama/commit/af37ff63d1e48be29c36d06aecb9faefd82648ed) where events that should have been registered using `RegisterEventHandler` were switched to `RegisterForUnhandledEvent`. This pull request restores the original behavior.
-   [x] My branch has a clear history of changes that can be easy to follow when being …
> Fix handled event regressions

- layout/hud/spectate.xml
- scripts/hud/spectate.ts
> Spectate right click cursor toggle fixes

- scripts/pages/leaderboards/leaderboards.ts
> Display sync track button on official map leaderboards

- scripts/pages/leaderboards/leaderboards.ts
- scripts/types-mom/events.d.ts
This also fixes an issue with the tracks dropdown not clearing when switching to a meta game mode with no maps.
-   [x] Fully tokenized all my strings (no hardcoded English strings!!) …
> Use new event for loading tracks on a local map leaderboards

- layout/pages/zoning/info.xml
- layout/pages/zoning/zoning.xml
- scripts/hud/tab-menu.ts
- scripts/pages/zoning/zoning.ts
- scripts/types-mom/events.d.ts
- scripts/types-mom/panels.d.ts
- styles/pages/zoning/zoning.scss
Closes:
momentum-mod/game/issues/2122
momentum-mod/game/issues/2225
This PR changes the UX around point placement while zoning and updates the UI accordingly. The region menu has been updated to remove tabs for points, properties, and teleport.
- Edit points in world space
- Click a corner to reposition it
- Click an edge midpoint to insert a corner
- Press backspace or delete to remove the last corner
- Change corner mode with middle click
- Creating zones now requires fewer clicks
-   [x] My branch …
> Zoning UI cleanup 2

- layout/pages/settings/gameplay.xml
- layout/pages/settings/input.xml
- layout/pages/settings/interface.xml
- layout/pages/settings/online.xml
- layout/pages/settings/settings.xml
- scripts/common/settings.ts
There's probably still a few things missing but this should at least get us more in sync with everything in 0.10. POEditor strings have been added already.
-   [ ] Fully tokenized all …
> Update settings to reflect 0.10 settings

- scripts/pages/end-of-run/end-of-run.ts
- scripts/pages/learn.ts
- scripts/types-mom/events.d.ts
Handles async saving of replays for end of run screen. Also fixed a couple of places where `mom_restart` was still being used.
-   [X] **I have thoroughly tested all of the code I have modified/added/removed to ensure something else did not break**
-   [X] I have followed [semantic commit messages](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716) e.g. `feat: Add foo`, `chore: Update bar`, etc...
-   [X] My branch has a clear history of changes that can be easy to follow when being reviewed commit-by-commit
-   [X] My branch is functionally complete; the only changes to be done will be those potentially requested in code review
-   [X] All changes requested in review have been `fixup`ed into my original commits.
-   [X] Fully tokenized all my strings (no hardcoded …
> Async replay saving

- layout/pages/settings/interface.xml
- Fixes incorrect strings for timer stop sound
- Removes unused sound fail settings
- Removed fail sound setting strings from POEditor already
-   [x] Fully tokenized all my strings (no …
> Fix incorrect sound settings

- scripts/common/timer.ts
- scripts/hud/status.ts
- scripts/types-mom/apis.d.ts
- scripts/types-mom/events.d.ts
- `OnControlledReplaySet` - fires when the controlled replay is set, replaced, or unset
- `GetReplayRunMetadata` - gets the RunMetadata for the controlled replay, if any (will be null if the controlled replay is not for a particular run)
- `RunMetadata.tempId` - can be used to tell runs apart
> Add OnControlledReplaySet, GetReplayRunMetadata, and RunMetadata tempId field

- scripts/types-mom/apis.d.ts
Basically the same thing, but better upholds the design goal of pano timer UI/HUD code only ever needing to think about and check "observed" data without being acutely aware of what the observed thing is.
Note that the new API is under `MomentumTimerAPI` rather than `MomentumReplayAPI`
> feat: Replace GetReplayRunMetadata with GetObservedRunMetadata

- layout/pages/zoning/zoning.xml
- scripts/common/web.ts
- scripts/pages/zoning/zoning.ts
- scripts/types-mom/events.d.ts
- scripts/types-mom/panels.d.ts
- styles/pages/zoning/zoning.scss
Closes momentum-mod/game/issues/2285
This pull request moves code that handles region edit state changes to c++. User facing changes:
- Unset region properties (bottom, height, safe height) are shown as blank instead of 0.00
- Deleting the last region in a zone allows the user to recreate the region for that zone. Zones are deleted from the tracklist (same as existing behavior)
- The binds list is updated to show `MOUSE2` and `ESCAPE` which function as a "back" button while editing/creating a region, and canceling the edit/creation of a region. The difference between back and cancel is subtle, cancel will always take the user straight to the menu.
Depends on red MR.
- …
> Move region edit state machine to c++

- scripts/pages/end-of-run/end-of-run.ts
Closes momentum-mod/game/issues/2306
Pretty easy to do with new events. The logic is a bit gross given the dependence on order of events firing but that seems to be very much by design in C++. Have tested pretty thoroughly.
Based on top of https://github.com/momentum-mod/panorama/pull/202
-   [x] My branch is functionally complete; the only changes to be done will be those potentially …
> Update End of Run page when new comparison is set

- scripts/hud/timer.ts
Small thing I just noticed. Main comparisons UI already does this check, forgot to do in the timer.
> Stop HUD timer comparing with self

- layout/pages/zoning/zoning.xml
- scripts/pages/zoning/zoning.ts
Closes momentum-mod/game/issues/2288
This pull request adds a checkbox to enable bhop on tracks.
This PR must be merged after state machine changes ([199](https://github.com/momentum-mod/panorama/pull/199))
-   [x] All changes requested in review have been `fixup`ed into …
> enable bhop on tracks

- layout/modals/context-menus/zoning-insert-zone.xml
- scripts/pages/zoning/zoning.ts
This PR adds the ability to right click a checkpoint in the zoning UI tracklist and insert a new zone before or after it. …
> Insert checkpoints at arbitrary position in tracklist

- scripts/common/online.ts
- scripts/modals/popups/lobby-create.ts
- scripts/modals/popups/lobby-settings.ts
- scripts/pages/drawer/lobby.ts
- scripts/types-mom/apis.d.ts
- scripts/util/event-definition.ts
Incorporates some API changes from the rewritten lobby system. We still need to update the localization tokens and their strings from "roaming lobby" to "map lobby".
> feat: Incorporate refreshed API from lobby system rewrite

- scripts/hud/comparisons.ts
- styles/hud/sticky-count.scss
This class gets applied when the stickybomb starts arming and transitions to the "armed" appearance after a set time, but this is incorrect in cases when watching a replay and then pausing or seeking. The animation was very subtle so this just removes it for now, and someone can hook up some transition styling later that is directly tied to arm time.
> fix: Don't animate sticky arming independently of game state

- scripts/hud/jump-timing.ts
- scripts/types-mom/events.d.ts
- Added support for new perf timing window
- Use events to update timing range and perf window
- Use a constant color for early timing since the speed penalty is now fixed
-   [ ] Fully …
> Jump timing improvements

- scripts/hud/cgaz.ts
This PR fixes an issue with the implementation of `mom_df_hud_prime_trueness` that prevented the hud from correctly calculating active and mirror zones separately while CPM turning.
- …
> Fix: prime sight part 2

- scripts/pages/drawer/drawer.ts
Disabled the profile drawer page for now since there's nothing in it. Didn't realise playercard logic was dependent on it. …
> Fix exception clicking on the topnav player card

- layout/hud/hud.xml
- layout/hud/tab-menu.xml
- layout/pages/zoning/zoning.xml
- scripts/common/web.ts
- scripts/hud/tab-menu.ts
- scripts/pages/zoning/zoning.ts
- scripts/types-mom/panels.d.ts
- styles/hud/hud.scss
- styles/hud/tab-menu.scss
- styles/pages/zoning/zoning.scss
- Change the zoning menu to be a standalone window instead of being an alternate mode of the tab menu. When `mom_zone_edit` is enabled, the zoning menu is always open rather than being tied to the tab menu bind. Instead of using the tab menu bind in combination with right click to lock the zoning menu open and interact with it, now while its open you just right click to capture the mouse to interact with it, and right or left click outside the menu to uncapture the mouse and go back to controlling the in-game camera. When the window is open but the mouse is not captured, the menu becomes translucent to not block the view as much and also make it especially clear whether the mouse is currently captured. This does make the "zone editing binds" info harder to read, but I plan to move this …
> Zoning menu layout rework and logic improvements

- scripts/hud/cgaz.ts
This pull request corrects the logic for selecting snap angles when CPM turning. The new logic only draws solid bars when a/d turning and the `CPM_TURN` flag (4) is active. When the flag is 0, the inactive strafe bars are shown as hints (same as original behavior).
- …
> display correct prime sight bars in a/d turns based on trueness setting

- scripts/pages/drawer/lobby.ts
This was a bug I introduced when porting to TypeScript. `member` was being redefined so code just assigned values from one object to itself. Using original `member` variable fixes it, also Object.assign is simpler way to do this.
> Fix map name and "user is typing" not updating lobby drawer

- scripts/pages/zoning/zoning.ts
This pull request fixes the following bugs:
- Setting user-defined TP destination seemed to not update/save
- Setting no target or a named entity as the targetname did not delete the destination position and yaw fields
Also, the pano code now has separate functions for reloading the properties data (text entries) and updating the zone defs because the user changed the dropdown selection.
- …
> fix TP destinations in Zoning UI

- layout/hud/keypress.xml
Closes https://github.com/momentum-mod/game/issues/2396
Since the jump and strafe counters will only be implemented on 0.12.0, it would be worth it reducing the visual noise on the corner and hide them until they are implemented.
break**
review
-   [x] All changes requested in review …
> fix: hide unimplemented counters on Key Press HUD

- scripts/util/register-for-gamemodes.ts
This never worked, but the HUD layout reloading behaviour meant it never got called. Seems to behave properly now with this fix and the reloading removed.
> fix: RegisterHUDPanelForGamemode throws on map load

- scripts/hud/status.ts
- scripts/types-mom/events.d.ts
When on a map with no zones I made it avoid showing "Timer Disabled" constantly, but with current code if you use practice mode or savelocs, it goes back to showing "Timer Disabled". This PR rewords that logic so it behaves consistently.
break**
review
-   [x] All changes requested in …
> Timer status small fixes

- scripts/hud/static-menu.ts
- scripts/pages/settings/settings.ts
Closes https://github.com/momentum-mod/game/issues/2419
Calling `UpdateCurrentAnimationKeyframes` call cause an infinite loop in a `CUtlMap::Find`. I have no idea how, was a huge pain to debug, and `UpdateCurrentAnimationKeyframes` really be used anyway, `TriggerClass` is the proper way to ensure an anim fires.
break**
-   [x] My branch is functionally complete; the only changes to be done will be …
> fix: replace usage of UpdateCurrentAnimationKeyframes with TriggerClass

- scripts/hud/strafe-trainer.ts
-   [ ] **I have thoroughly tested all of the code I have modified/added/removed to ensure something else did not
break**
-   [ ] I have followed [semantic commit messages](https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716)
-   [ ] My branch is functionally complete; the only changes to be done will be those potentially requested in code
review
-   [ ] Fully tokenized all my strings (no hardcoded English strings!!) and supplied
[bulk JSON strings](https://docs.momentum-mod.org/guide/localization/#bulk-adding-terms) below
> Enable strafe trainer on HL1 Bhop and Climb 1.6

- scripts/pages/zoning/zoning.ts
Closes momentum-mod/game/issues/2447
This pull request adds UI for creating overbounce zones as global regions. This is already implemented in the engine, an needed to be added to the in-game zoning tool.
break**
review
-   [ ] All changes requested in review have been `fixup`ed into …
> feat: add overbounce global regions to zoning UI

- scripts/pages/drawer/lobby.ts
- scripts/types-mom/apis.d.ts
- scripts/types-mom/panels.d.ts
Closes momentum-mod/game/issues/2456
This cast to number loses precision for steamIDs which exceed 2^53. Should always be string here, my fault for not doing the ChatAPI.ChangeMuteState definition wrong.
break**
review
-   [x] All changes requested in review have been `fixup`ed into my …
> fix: muting not working in lobbies

- layout/hud/tab-menu.xml
Recent change broke opening zoning UI from the tab menu. This PR undoes the change that broke it.
> fix: open zoning UI from tab menu

- layout/pages/zoning/zoning.xml
- scripts/pages/zoning/zoning.ts
- scripts/types-mom/panels.d.ts
- styles/pages/zoning/zoning.scss
Closes momentum-mod/game/issues/2452
This pull request implements the following changes:
- keep scroll position of selection lists when new zoning object is selected
- include global regions when counting total regions (c++ validator also uses this behavior)
- don't require the user to submit changes to test entry fields
- ~~teleport to region when new zoning object is selected (don't require double click)~~ discarded change
- add a new button for previewing a teleport destination
- when teleporting to view a region, use the improved teleport (don't send the user to the TP destination)
- when the user teleports to a defrag bonus, use the main track's zones
Requires red MR for teleport features to be merged.
-   [x] **I have thoroughly tested all of the code I have modified/added/removed …
> Maintain scroll position after updating selection
